/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alexis' at '23/02/16 10:40' with Gradle 2.6
 *
 * @author Alexis, @date 23/02/16 10:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
